const {
	REACT_APP_APIKEY,
	REACT_APP_AUTH_DOMAIN,
	REACT_APP_STORAGEBUCKET,
	REACT_APP_PROJECTID,
	REACT_APP_MESSAGING_SENDERID,
	REACT_APP_APPID,
	REACT_APP_MEASUREMENTID,
} = process.env;

const config = {
	APIKEY: REACT_APP_APIKEY,
	AUTH_DOMAIN: REACT_APP_AUTH_DOMAIN,
	PROJECTID: REACT_APP_PROJECTID,
	STORAGEBUCKET: REACT_APP_STORAGEBUCKET,
	MESSAGING_SENDERID: REACT_APP_MESSAGING_SENDERID,
	APPID: REACT_APP_APPID,
	MEASUREMENTID: REACT_APP_MEASUREMENTID,
};

export default config;
